apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-hse-openshift
  namespace: netdot
data:
  OpenShiftConfig.yml: |-
    ResolvedPlaceholderFromEnvVariables: "${PATH?NotFound}"
    UnresolvedPlaceholder: "${SomKeyNotFound?NotFound}"
    ResolvedPlaceholderFromJson: "${Logging:LogLevel:System?${Loggin:LogLevel:Default}}"
    ConfiguracionDeJson: Valor por defecto
  tres.yml: |-
    Logging:
      LogLevel:
        Default: Information
        Microsoft: Warning
        app: Trace
