apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-hse-openshift
  namespace: netdot
data:
  application.properties: |-
{
  "ResolvedPlaceholderFromEnvVariables": "${PATH?NotFound}",
  "UnresolvedPlaceholder": "${SomKeyNotFound?NotFound}",
  "ResolvedPlaceholderFromJson": "${Logging:LogLevel:System?${Loggin:LogLevel:Default}}",
  "ConfiguracionDeJson": "Valor por defecto"
}
